In [2]:
import numpy as np
import pandas as pd

In [3]:
#DATAFRAMES: when you combine multiple series together they called a dataframes

In [4]:
#CREATING A DATAFRAMES

In [6]:
data = {
    'Name' : ['Neha', 'Priya', 'Vidhi', 'Gaurav'],
    'Age' : [23, 24, 23, 25],
    'City' : ['Delhi' , 'Bihar', 'UP', 'Dwarka'],
    'Salary' : [65000, 55000, 56000, 35000]
}
df = pd.DataFrame(data)

In [7]:
df

     Name  Age    City  Salary
0    Neha   23   Delhi   65000
1   Priya   24   Bihar   55000
2   Vidhi   23      UP   56000
3  Gaurav   25  Dwarka   35000

In [18]:
data_list = [
    ['Neha', 23, 'Delhi', 65000],
    ['Priya', 24, 'Bihar', 55000],
    ['Vidhi', 23, 'UP',	56000],
    ['Gaurav' , 25,	'Dwarka' ,35000]
]
df2 = pd.DataFrame(data_list)
df2
column = ["Name", "Age", "City", "Salary"]
df2 = pd.DataFrame(data_list, columns= column)
df2

     Name  Age    City  Salary
0    Neha   23   Delhi   65000
1   Priya   24   Bihar   55000
2   Vidhi   23      UP   56000
3  Gaurav   25  Dwarka   35000

In [19]:
#SELECTING AND INDEXING OF COLUMNS

In [21]:
df2[["Name", "Age"]]

     Name  Age
0    Neha   23
1   Priya   24
2   Vidhi   23
3  Gaurav   25

In [ ]:
#CREATING A NEW COLUMNS

In [22]:
df2

     Name  Age    City  Salary
0    Neha   23   Delhi   65000
1   Priya   24   Bihar   55000
2   Vidhi   23      UP   56000
3  Gaurav   25  Dwarka   35000

In [28]:
df2["Designation"] = ["Software Egineer", "Developer", "Doctor", "Manager"]
df2

     Name  Age    City  Salary       Designation
0    Neha   23   Delhi   65000  Software Egineer
1   Priya   24   Bihar   55000         Developer
2   Vidhi   23      UP   56000            Doctor
3  Gaurav   25  Dwarka   35000           Manager

In [ ]:
#REMOVING COLUMNS

In [29]:
df2.drop('Designation', axis = 1,inplace=True)

In [30]:
df2

     Name  Age    City  Salary
0    Neha   23   Delhi   65000
1   Priya   24   Bihar   55000
2   Vidhi   23      UP   56000
3  Gaurav   25  Dwarka   35000

In [ ]:
#SELECTING ROWS

In [31]:
df2

     Name  Age    City  Salary
0    Neha   23   Delhi   65000
1   Priya   24   Bihar   55000
2   Vidhi   23      UP   56000
3  Gaurav   25  Dwarka   35000

In [34]:
df2.loc[[0,1,2]]

    Name  Age   City  Salary
0   Neha   23  Delhi   65000
1  Priya   24  Bihar   55000
2  Vidhi   23     UP   56000

In [ ]:
#SELECTING SUBSETS OF ROWS AND COLUMNS

In [35]:
df2

     Name  Age    City  Salary
0    Neha   23   Delhi   65000
1   Priya   24   Bihar   55000
2   Vidhi   23      UP   56000
3  Gaurav   25  Dwarka   35000

In [36]:
df2.loc[[0,1]][["City", "Salary"]]

    City  Salary
0  Delhi   65000
1  Bihar   55000

In [37]:
df2.loc[[2,3]][["Name", "Age"]]

     Name  Age
2   Vidhi   23
3  Gaurav   25

In [ ]:
#CONDITIONAL SELECTION

In [38]:
df2

     Name  Age    City  Salary
0    Neha   23   Delhi   65000
1   Priya   24   Bihar   55000
2   Vidhi   23      UP   56000
3  Gaurav   25  Dwarka   35000

In [39]:
df2[df2["Age"] > 24]

     Name  Age    City  Salary
3  Gaurav   25  Dwarka   35000

In [43]:
df2[(df2["Age"] <= 23) & (df2["City"] == "Delhi")]

   Name  Age   City  Salary
0  Neha   23  Delhi   65000