In [1]:
import numpy as np
import pandas as pd

In [ ]:
# Finding MissingData

In [9]:
data = {
    'A' : [1, 2, np.nan, 4, 5],
    'B' : [1, 2, 3, 4, 5],
    'C' : [1, 2, 3, np.nan, np.nan],
    'D' : [1 , np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [10]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [11]:
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [12]:
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

In [13]:
# Removing Missing Data

In [14]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [15]:
df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [21]:
df.dropna(thresh= 3)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

In [ ]:
# Filling the missign data

In [22]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [23]:
df.fillna(0)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [24]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [25]:
value = {'A' : 0, 'B' : 100, 'C' : 200, 'D' : 300}
df.fillna(value= value)

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  300.0
2  0.0  3    3.0  300.0
3  4.0  4  200.0  300.0
4  5.0  5  200.0    5.0

In [26]:
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0