In [1]:
import numpy as np
import pandas as pd

In [2]:
# Merging 2 dataframe

In [6]:
employees = pd.DataFrame({
    'employee_id': [1,2,3,4,5],
    'name' : ['john', 'neha', 'priya', 'bebo', 'lucky'],
    'department' : ['HR', 'IT', 'Finance','HR', 'IT']
})
salaries = pd.DataFrame({
    'employee_id': [1,2,3,6,7],
    'salary' : [60000, 80000, 65000, 70000, 90000],
    'bonus' : [500, 10000, 2000, 5000, 1200 ]
})

In [4]:
employees

   employee_id   name department
0            1   john         HR
1            2   neha         IT
2            3  priya    Finance
3            4   bebo         HR
4            5  lucky         IT

In [7]:
salaries

   employee_id  salary  bonus
0            1   60000    500
1            2   80000  10000
2            3   65000   2000
3            6   70000   5000
4            7   90000   1200

In [10]:
pd.merge(employees,salaries,on='employee_id',how='inner')

   employee_id   name department  salary  bonus
0            1   john         HR   60000    500
1            2   neha         IT   80000  10000
2            3  priya    Finance   65000   2000

In [11]:
pd.merge(employees,salaries,on='employee_id',how='outer')

   employee_id   name department   salary    bonus
0            1   john         HR  60000.0    500.0
1            2   neha         IT  80000.0  10000.0
2            3  priya    Finance  65000.0   2000.0
3            4   bebo         HR      NaN      NaN
4            5  lucky         IT      NaN      NaN
5            6    NaN        NaN  70000.0   5000.0
6            7    NaN        NaN  90000.0   1200.0

In [12]:
pd.merge(employees,salaries,on='employee_id',how='left')

   employee_id   name department   salary    bonus
0            1   john         HR  60000.0    500.0
1            2   neha         IT  80000.0  10000.0
2            3  priya    Finance  65000.0   2000.0
3            4   bebo         HR      NaN      NaN
4            5  lucky         IT      NaN      NaN

In [13]:
pd.merge(employees,salaries,on='employee_id',how='right')

   employee_id   name department  salary  bonus
0            1   john         HR   60000    500
1            2   neha         IT   80000  10000
2            3  priya    Finance   65000   2000
3            6    NaN        NaN   70000   5000
4            7    NaN        NaN   90000   1200

In [ ]:
#Concatination od 2 dataframe

In [14]:
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B' : ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B' : ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

In [15]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [16]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [18]:
pd.concat([df1,df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [19]:
pd.concat([df1,df2], axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

In [ ]:
#Joining of 2 DataFrame

In [20]:
df1 = pd.DataFrame({
    'name': ['Alice', 'bob', 'Charlie']
}, index=[1,2,3])

df2 = pd.DataFrame({
    'score': [85,90,75]
}, index= [2,3,4])

In [21]:
df1

      name
1    Alice
2      bob
3  Charlie

In [22]:
df2

   score
2     85
3     90
4     75

In [23]:
df1.join(df2)

      name  score
1    Alice    NaN
2      bob   85.0
3  Charlie   90.0

In [24]:
df1.join(df2,how='outer')

      name  score
1    Alice    NaN
2      bob   85.0
3  Charlie   90.0
4      NaN   75.0